### ISSUE TITLE
How to send people from Proxy1 servers to Proxy2 servers?

### ISSUE THREAD

**Issue by Tim-Rambo** [RedisMC/RedisBungee#20]
## What is your question?
How to send people from Proxy1 servers to Proxy2 servers?

Wat I have tried:

I have redis running with both Proxy1 and Proxy2 connected to it.
Proxy2 receives the /sendtoall cmd but does not send me to the server called spawn.
/serverids reports back both proxies

Hope this information helps.
Thanks in advanced.

**Comment by ham1255** [comment]
You cant this limitation of minecraft java, *no tranfer packet*

While bedrock version has way to change connected server.

**Comment by ham1255** [comment]
Use round robin for your setup in cloudflare etc.
